--workbook에 만들 테이블 생성
CREATE TABLE COMPANY(
    COMPANY_ID NUMBER PRIMARY KEY, 
    COMPANY_NAME VARCHAR2(100) NOT NULL, 
    COMPANY_ADDRESS VARCHAR2(55), 
    COMPANY_PHONE VARCHAR2(20)
);
--Table COMPANY이(가) 생성되었습니다.

SELECT * FROM COMPANY;

--COMPANY를 ALTER를 이용해서 테이블명 COMPANY1로 변경
ALTER TABLE COMPANY RENAME TO COMPANY1;
--Table COMPANY이(가) 변경되었습니다.

SELECT * FROM COMPANY1;
/*
★ 오류가 발생한 코드
SELECT * FROM COMPANY;
★ 오류코드
ORA-00942: table or view does not exist
★ 원인
테이블명을 COMPANY에서 COMPANY1으로 변경했기 때문에
★ 문제 해결한 코드
SELECT * FROM COMPANY1;
*/

--COMPANY 시퀀스 생성 COMPANY_SEQ, 시작값1, 증가값1, NOCACHE, NOCYCLE
--방법1
CREATE SEQUENCE COMPANY_SEQ;
--Sequence COMPANY_SEQ이(가) 생성되었습니다.

--방법2
CREATE SEQUENCE COMPANY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE
;
--Sequence COMPANY_SEQ이(가) 생성되었습니다.

--INSERT COMPANY 회사 추가
INSERT INTO COMPANY1
VALUES (COMPANY_SEQ.NEXTVAL, '햇에제과', '서울시 강남구', '02-1234-5678');
--1 행 이(가) 삽입되었습니다.

INSERT INTO COMPANY1
VALUES (COMPANY_SEQ.NEXTVAL, '롯에제과', '서울시 중구', '02-2345-6789');
--1 행 이(가) 삽입되었습니다.

INSERT INTO COMPANY1
VALUES (COMPANY_SEQ.NEXTVAL, '올이온', '서울시 용구', '02-3456-7890');
--1 행 이(가) 삽입되었습니다.

--확인하기
SELECT * FROM COMPANY1;

--SNACKS 테이블 생성
CREATE TABLE SNACKS (
    SNACK_ID NUMBER(10, 0) PRIMARY KEY, --과자 ID (기본키)
    SNACK_NAME VARCHAR2(100) NOT NULL, --과자 이름 (NULL 불가)
    PRICE NUMBER(10, 2) NOT NULL, --가격 (NULL 불가) 
    COMPANY_ID NUMBER(10, 0), 
    CONSTRAINT COMPANY1 FOREIGN KEY (COMPANY_ID)
    REFERENCES COMPANY1(COMPANY_ID) --부모키 삭제시 자식키 삭제
);
--Table SNACKS이(가) 생성되었습니다.

SELECT * FROM COMPANY1;
SELECT * FROM SNACKS;

--SNACKS_SEQ 시퀀스 생성, 시작값1, 증가값1, NOCACHE, NOCYCLE
CREATE SEQUENCE SNACKS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE
;
--Sequence SNACKS_SEQ이(가) 생성되었습니다.

--SNACKS_SEQ.NEXTVAL을 이용해서 INSERT 해주기
INSERT INTO SNACKS VALUES (SNACKS_SEQ.NEXTVAL, '오에스', 1500, '1');
INSERT INTO SNACKS VALUES (SNACKS_SEQ.NEXTVAL, '칸조', 1220, '1');
INSERT INTO SNACKS VALUES (SNACKS_SEQ.NEXTVAL, '배배로', 1100, '2');
INSERT INTO SNACKS VALUES (SNACKS_SEQ.NEXTVAL, '조고파이', 2000, '2');

SELECT * FROM SNACKS;

--가격이 1500 이상인 과자 조회
SELECT * 
FROM SNACKS
WHERE PRICE >= 1500;

--서울시 강남구에 위치한 회사 조회
SELECT *
FROM COMPANY1
WHERE COMPANY_ADDRESS = '서울시 강남구';

--회사 ID가 1인 과자 조회
SELECT * 
FROM SNACKS
WHERE COMPANY_ID = '1';

--회사 ID가 1이고, 그 회사의 과자들 조회
--방법1
SELECT SNACK_NAME AS "과자이름", PRICE AS "과자가격", COMPANY_NAME AS "회사이름"
FROM COMPANY1 c, SNACKS s
WHERE c.COMPANY_ID = s.COMPANY_ID AND c.COMPANY_ID = 1;

--방법2
SELECT s.SNACK_NAME AS "과자이름", s.PRICE AS "과자가격", c.COMPANY_NAME AS "회사이름"
FROM COMPANY1 c
JOIN SNACKS s ON c.COMPANY_ID = s.COMPANY_ID
WHERE c.COMPANY_ID = 1;