CREATE TABLE MEMBER2 (
    MEMBER_ID NUMBER PRIMARY KEY,
    MEMBER_NAME VARCHAR2(50 BYTE) NOT NULL,
    MEMBER_AGE NUMBER NOT NULL,
    MEMBER_PHONE VARCHAR2(20 BYTE) NOT NULL
);

CREATE SEQUENCE MEMBER2_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO MEMBER2 (MEMBER_ID, MEMBER_NAME, MEMBER_AGE, MEMBER_PHONE) 
VALUES (MEMBER2_SEQ.NEXTVAL, '가나다', 30, '01012345678');
INSERT INTO MEMBER2 (MEMBER_ID, MEMBER_NAME, MEMBER_AGE, MEMBER_PHONE) 
VALUES (MEMBER2_SEQ.NEXTVAL, '동그라미', 10, '010-1111-1111');

SELECT * FROM member2;